name: ap
channels:
  - defaults
dependencies:
  - python=3.9.18
  - pip=23.3.1
  - pip:  
    - numpy==1.23.1
    - spacy==3.3.0
    - typing-inspect==0.8.0
    - typing_extensions==4.5.0
    - unidecode==1.3.4